on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: cmake
      uses: lukka/get-cmake@latest
    - name: vcpkg
      uses: lukka/run-vcpkg@v11
    - name: build
      uses: lukka/run-cmake@v10
      with:  
        workflowPreset: ci
