name: CMake
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: cmake
      uses: lukka/get-cmake@latest
    - name: vcpkg
      uses: lukka/run-vcpkg@v11
    - name: configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build ${{github.workspace}}/build
    - name: test
      working-directory: ${{github.workspace}}/build
      run: ctest
